### ISSUE TITLE
Server Crashes after a while

### ISSUE THREAD

**Issue by coxtor** [rhasspy/rhasspy-speakers-cli-hermes#10]
Hi after a while of running Rhasspy, the Hermes server crashes with following error and remains nonfunctional until I restart Rhasspy.

```
[DEBUG:2020-10-18 06:04:26,553] rhasspyserver_hermes: Handling Voices (topic=rhasspy/tts/voices, id=1a5a64c8-2e2d-499b-84b8-b498d32cda87)
[ERROR:2020-10-18 06:04:46,429] rhasspyserver_hermes: 
Traceback (most recent call last):
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 866, in api_listen_for_command
    handle_captured(), messages, message_types
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 960, in publish_wait
    result_awaitable, timeout=timeout_seconds
  File "/usr/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

**Comment by coxtor** [comment]
wrong repository sorry.
